import type { LicenseSnapshot, Plan } from './license-contract';

export type Language = 'th' | 'en';
export type Settings = { language: Language; highContrast: boolean; fullscreen: boolean };
export type AppStatus = { version: string; settings: Settings; lastError: string | null };
export type GuestDisplayPayload = { language: Language; eventName: string; status: 'ready' | 'connecting' | 'disconnected' | 'countdown' | 'capturing' | 'review'; mediaMode: 'photo' | 'video'; countdown: number | null; resultCount: number; previewDataUrl: string; qrDataUrl: string; message: string };
export type PhotoCloudProgress = { sessionId: string; completed: number; total: number; uploadedCount: number };
export type PhotoStorageStatus = { configured: boolean; directoryName: string | null; photoCount: number; pendingRecovery: number; needsAttention: boolean };
export type PhotoRecoveryIssue = { kind: 'orphan-photo' | 'incomplete-write' | 'index-temp' | 'missing-photo' | 'invalid-index' | 'storage-unavailable'; id: string | null; token?: string };
export type SavedPhoto = { id: string; width: number; height: number; byteLength: number; sha256: string; savedAt: string; eventId?: string; cloudUploaded?: boolean };
export type PhotoRecord = SavedPhoto & { fileName: string; mimeType: 'image/jpeg' };
export type SavedVideo = { id: string; width: number; height: number; byteLength: number; durationMs: number; sha256: string; savedAt: string; eventId?: string; cloudUploaded?: boolean };
export type VideoRecord = SavedVideo & { fileName: string; mimeType: 'video/webm' };
export type PhotoboothEvent = { id: string; name: string; date: string | null; notes: string; createdAt: string; updatedAt: string };
export type PhotoboothEventWithCount = PhotoboothEvent & { photoCount: number };
export type CaptureTextLayer = { id: string; text: string; x: number; y: number; width: number; fontSize: number; color: string; align: 'left' | 'center' | 'right' };
export type CaptureImageLayer = { id: string; src: string; x: number; y: number; width: number; height: number };
export type CaptureTemplateSnapshot = { id: string; name: string; count: 1 | 2 | 4; title: string; footer: string; background: string; frame: string; showDate: boolean; overlay?: string; slots?: Array<{ x: number; y: number; width: number; height: number }>; textLayers?: CaptureTextLayer[]; videoFrame?: { x: number; y: number; width: number; height: number }; videoTextLayers?: CaptureTextLayer[]; imageLayers?: CaptureImageLayer[]; videoImageLayers?: CaptureImageLayer[] };
export type CaptureSessionRecord = { id: string; eventId: string | null; template: CaptureTemplateSnapshot | null; photoIds: string[]; compositionPhotoId?: string; videoIds?: string[]; status: 'capturing' | 'review' | 'confirmed' | 'interrupted' | 'cancelled' | 'retaken'; createdAt: string; updatedAt: string };
export type Bridge = {
  isMacOS: boolean;
  getStatus(): Promise<AppStatus>;
  saveSettings(value: Settings): Promise<Settings>;
  setFullscreen(value: boolean): Promise<boolean>;
  listDisplays(): Promise<Array<{ id: number; label: string; width: number; height: number; primary: boolean; current: boolean }>>;
  openGuestDisplay(displayId?: number): Promise<boolean>;
  closeGuestDisplay(): Promise<boolean>;
  isGuestDisplayOpen(): Promise<boolean>;
  publishGuestDisplay(payload: GuestDisplayPayload): Promise<boolean>;
  onGuestDisplayUpdate(listener: (payload: GuestDisplayPayload) => void): () => void;
  getPhotoStorageStatus(): Promise<PhotoStorageStatus>;
  inspectPhotoRecovery(): Promise<PhotoRecoveryIssue[]>;
  importRecoveredPhoto(id: string): Promise<boolean>;
  quarantineRecoveryItem(kind: 'incomplete-write' | 'index-temp', token: string): Promise<boolean>;
  rebuildPhotoIndex(): Promise<number | null>;
  choosePhotoStorage(): Promise<PhotoStorageStatus>;
  openPhotoStorage(): Promise<boolean>;
  beginCapture(photoCount?: number, template?: CaptureTemplateSnapshot | null, mediaMode?: 'photo' | 'video'): Promise<{ authorizationId: string; sessionId: string; cloudShareUrl: string | null }>;
  cancelCapture(captureAuthorization: string): Promise<boolean>;
  savePhoto(jpegBytes: Uint8Array, captureAuthorization: string): Promise<SavedPhoto>;
  saveComposition(jpegBytes: Uint8Array, sessionId: string): Promise<SavedPhoto>;
  saveVideo(webmBytes: Uint8Array, width: number, height: number, durationMs: number, captureAuthorization: string): Promise<SavedVideo>;
  readVideo(id: string): Promise<{ video: VideoRecord; webmBytes: Uint8Array }>;
  exportVideo(id: string): Promise<boolean>;
  listCaptureSessions(limit?: number): Promise<CaptureSessionRecord[]>;
  completeCaptureSession(sessionId: string, status: 'review' | 'confirmed' | 'cancelled' | 'retaken'): Promise<CaptureSessionRecord | null>;
  syncPhotoCloudSession(sessionId: string): Promise<{ shareUrl: string | null; uploadedCount: number; mediaCount: number; photoCount: number; videoCount: number }>;
  onPhotoCloudProgress(listener: (progress: PhotoCloudProgress) => void): () => void;
  getPhotoCloudShareUrl(sessionId: string): Promise<string | null>;
  getPhotoCloudShareStatus(sessionId: string): Promise<{ shareUrl: string | null; revoked: boolean; expiresAt: string | null }>;
  revokePhotoCloudShare(sessionId: string): Promise<boolean>;
  listPhotos(offset?: number, limit?: number, eventId?: string | null): Promise<PhotoRecord[]>;
  readPhoto(id: string): Promise<{ photo: PhotoRecord; jpegBytes: Uint8Array }>;
  exportPhoto(id: string): Promise<boolean>;
  deletePhoto(id: string): Promise<boolean>;
  getLicenseStatus(): Promise<LicenseSnapshot>;
  getLicensePlans(): Promise<Plan[]>;
  activateLicense(licenseKey: string): Promise<LicenseSnapshot>;
  deactivateLicense(): Promise<boolean>;
  listEvents(): Promise<{ events: PhotoboothEventWithCount[]; activeEventId: string | null }>;
  createEvent(value: { name: string; date: string | null; notes: string }): Promise<PhotoboothEvent>;
  updateEvent(id: string, value: { name: string; date: string | null; notes: string }): Promise<PhotoboothEvent>;
  deleteEvent(id: string): Promise<boolean>;
  setActiveEvent(id: string | null): Promise<PhotoboothEvent | null>;
};
